import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, Award, BookOpen, Check, ChevronRight, CircleHelp, LockKeyhole, ShieldCheck, Sparkles, UserRound } from 'lucide-react';
import { createAssessment } from './assessment';

const initialAccount = { name:'', email:'', phone:'', password:'', terms:false };
const initialProfile = { organization:'', designation:'', role:'', assignment:'', experience:'', education:'', domain:'', training:'', techSkills:[], goal:'' };
const skills = ['Python','SQL','R','Excel','Data Visualization','Machine Learning'];
const levels = [['Beginner','Core concepts and everyday data work'],['Intermediate','Applied analysis and informed decisions'],['Advanced','Complex analysis, governance and AI']];
const profileSuggestions = {
  organization: ['Ministry of Statistics and Programme Implementation (MoSPI)','National Statistical Office (NSO)','National Statistical Systems Training Academy (NSSTA)','Field Operations Division (FOD), NSO','Data Informatics and Innovation Division (DIID), MoSPI','State Directorate of Economics and Statistics','Planning Department / Planning Commission','Ministry / Department statistical unit','Public sector undertaking','University or research institution'],
  designation: ['Junior Statistical Officer (JSO)','Statistical Investigator','Statistical Officer','Senior Statistical Officer','Assistant Director','Deputy Director','Director','Data Entry Operator','Research Officer','Programme Officer','Consultant / Analyst'],
  role: ['Data Analyst','Statistician','Survey Officer','Field Investigator','Data Manager','Research Analyst','Monitoring & Evaluation Officer','Policy Analyst','Dashboard / MIS Officer','IT / Systems Officer','Trainer / Faculty'],
  assignment: ['Periodic Labour Force Survey (PLFS)','Consumer Price Index (CPI)','Annual Survey of Industries (ASI)','Household Consumption Expenditure Survey (HCES)','National Accounts / GDP estimates','Economic Census','Population Census / demographic statistics','Health and social statistics','Agriculture and environment statistics','Data quality, validation or dissemination','Dashboard / MIS development']
};
function Field({label,name,value,onChange,type='text',placeholder,required=true}) { return <label className="field"><span>{label}{required && <b> *</b>}</span><input type={type} name={name} value={value} onChange={onChange} placeholder={placeholder}/></label>; }
function SuggestionField({label,name,value,onChange,placeholder,required=true,options=[]}) { const listId=`${name}-suggestions`; return <label className="field"><span>{label}{required && <b> *</b>}</span><input name={name} value={value} onChange={onChange} placeholder={placeholder} list={listId}/><datalist id={listId}>{options.map(option=><option value={option} key={option}/>)}</datalist></label>; }
function ErrorList({errors}) { const messages=[...new Set(Object.values(errors))]; return messages.length ? <div className="errors">{messages.map(x=><p key={x}>{x}</p>)}</div> : null; }

export default function App() {
  const stored = (()=>{try{return JSON.parse(localStorage.getItem('technova-onboarding'))||{};}catch{return {};}})();
  const [stage,setStage]=useState(stored.stage||1), [account,setAccount]=useState({...initialAccount,...stored.account}), [profile,setProfile]=useState({...initialProfile,...stored.profile}), [level,setLevel]=useState(stored.level||'Intermediate'), [questions,setQuestions]=useState([]), [answers,setAnswers]=useState({}), [errors,setErrors]=useState({}), [submitted,setSubmitted]=useState(false);
  useEffect(()=>localStorage.setItem('technova-onboarding',JSON.stringify({stage,account,profile,level})),[stage,account,profile,level]);
  const accountChange=e=>setAccount(x=>({...x,[e.target.name]:e.target.type==='checkbox'?e.target.checked:e.target.value}));
  const profileChange=e=>setProfile(x=>({...x,[e.target.name]:e.target.value}));
  const nextAccount=()=>{const e={}; ['name','email','phone','password'].forEach(k=>!account[k]&&(e[k]='Please complete this field.')); if(account.email&&!/^\S+@\S+\.\S+$/.test(account.email))e.email='Enter a valid email address.';if(account.password&&account.password.length<8)e.password='Use at least 8 characters.';if(!account.terms)e.terms='Please accept the terms to continue.';setErrors(e);if(!Object.keys(e).length)setStage(2);};
  const nextProfile=()=>{const e={};['organization','designation','role','assignment','experience','education','domain'].forEach(k=>!profile[k]&&(e[k]='Please complete this field.'));if(!profile.techSkills.length)e.techSkills='Choose at least one technology skill.';setErrors(e);if(!Object.keys(e).length)setStage(3);};
  const toggleSkill=skill=>setProfile(x=>({...x,techSkills:x.techSkills.includes(skill)?x.techSkills.filter(y=>y!==skill):[...x.techSkills,skill]}));
  const start=()=>{setQuestions(createAssessment(profile,level));setAnswers({});setSubmitted(false);setStage(4);window.scrollTo(0,0);};
  const score=questions.reduce((n,q)=>n+(answers[q.id]===q.answer?1:0),0);
  const restart=()=>{localStorage.removeItem('technova-onboarding');setStage(1);setAccount(initialAccount);setProfile(initialProfile);setQuestions([]);setAnswers({});setSubmitted(false);};
  if(stage===5)return <Results {...{account,profile,score,total:questions.length,restart}}/>;
  return <main className="shell"><header><a className="brand" href="/" onClick={e=>e.preventDefault()}><span>TN</span> Tech Nova</a><div className="secure"><LockKeyhole size={15}/> Secure onboarding</div></header>{stage<=3&&<><section className="progress-label"><span>Step {stage} of 3</span><strong>{['Account','Professional profile','Competency check'][stage-1]}</strong></section><div className="progress-track"><i style={{width:`${stage/3*100}%`}}/></div></>}<section className="content">{stage===1&&<Account {...{account,accountChange,errors,nextAccount}}/>}{stage===2&&<Profile {...{profile,profileChange,toggleSkill,errors,nextProfile,setStage}}/>}{stage===3&&<Level {...{profile,level,setLevel,setStage,start}}/>}{stage===4&&<Assessment {...{questions,answers,setAnswers,submitted,setSubmitted,setStage,setStage,finish:()=>setStage(5)}}/>}</section></main>;
}
function Account({account,accountChange,errors,nextAccount}) {return <div className="panel narrow"><div className="eyebrow"><Sparkles size={16}/> YOUR LEARNING JOURNEY STARTS HERE</div><h1>Create your Tech Nova account</h1><p className="lead">Build a learning profile designed around the work you do.</p><button className="google" onClick={()=>alert('Google sign-in is a visual demo in this frontend-only prototype.')}><span className="google-mark">G</span> Continue with Google</button><div className="or"><span>or continue with email</span></div><div className="form-grid"><Field label="Full name" name="name" value={account.name} onChange={accountChange} placeholder="Your full name"/><Field label="Work email" name="email" type="email" value={account.email} onChange={accountChange} placeholder="name@organisation.gov"/><Field label="Mobile number" name="phone" type="tel" value={account.phone} onChange={accountChange} placeholder="Your mobile number"/><Field label="Create password" name="password" type="password" value={account.password} onChange={accountChange} placeholder="At least 8 characters"/></div><ErrorList errors={errors}/><label className="check"><input name="terms" type="checkbox" checked={account.terms} onChange={accountChange}/><span>I agree to the terms of use and privacy notice.</span></label><button className="primary full" onClick={nextAccount}>Continue <ArrowRight size={18}/></button><p className="small"><ShieldCheck size={14}/> Information is used only to personalize your learning path.</p></div>}
function Profile({profile,profileChange,toggleSkill,errors,nextProfile,setStage}) {const selects={experience:['0–1 years','2–4 years','5–7 years','8+ years'],education:['Higher secondary','Diploma',"Bachelor's degree","Master's degree",'Doctorate / PhD'],domain:['Labour Statistics','Population & Demography','Economic Statistics','Health Statistics','Agriculture & Environment']};return <div className="panel"><div className="eyebrow"><UserRound size={16}/> PROFESSIONAL PROFILE</div><h1>Tell us about your work</h1><p className="lead">Choose a suggestion or type a different value—we’ll use it to make the competency check relevant to your work.</p><div className="form-grid three"><SuggestionField label="Department or organization" name="organization" value={profile.organization} onChange={profileChange} placeholder="Search or choose an organization" options={profileSuggestions.organization}/><SuggestionField label="Designation" name="designation" value={profile.designation} onChange={profileChange} placeholder="Search or choose a designation" options={profileSuggestions.designation}/><SuggestionField label="Job role" name="role" value={profile.role} onChange={profileChange} placeholder="Search or choose a role" options={profileSuggestions.role}/><SuggestionField label="Current assignment" name="assignment" value={profile.assignment} onChange={profileChange} placeholder="Search or choose an assignment" options={profileSuggestions.assignment}/>{Object.entries(selects).map(([name,values])=><label className="field" key={name}><span>{name==='experience'?'Years of experience':name==='education'?'Education':'Statistical domain'} <b>*</b></span><select name={name} value={profile[name]} onChange={profileChange}><option value="">Select an option</option>{values.map(x=><option key={x}>{x}</option>)}</select></label>)}</div><div className="field wide"><span>Technology skills <b>*</b></span><div className="skills">{skills.map(skill=><button className={profile.techSkills.includes(skill)?'skill selected':'skill'} key={skill} onClick={()=>toggleSkill(skill)}>{profile.techSkills.includes(skill)&&<Check size={14}/>} {skill}</button>)}</div></div><div className="form-grid extra"><Field label="Previous training (optional)" required={false} name="training" value={profile.training} onChange={profileChange} placeholder="Courses, workshops or certifications"/><Field label="Learning goal (optional)" required={false} name="goal" value={profile.goal} onChange={profileChange} placeholder="What would you like to achieve?"/></div><ErrorList errors={errors}/><div className="actions"><button className="secondary" onClick={()=>setStage(1)}><ArrowLeft size={18}/> Back</button><button className="primary" onClick={nextProfile}>Continue <ArrowRight size={18}/></button></div></div>}
function Level({profile,level,setLevel,setStage,start}) {return <div className="panel narrow"><div className="eyebrow"><CircleHelp size={16}/> PERSONALIZED COMPETENCY CHECK</div><h1>Choose your starting level</h1><p className="lead">We created a question set for a <strong>{profile.designation||'professional'}</strong> working in <strong>{profile.domain||'your domain'}</strong>.</p><div className="level-list">{levels.map(([name,description])=><button className={level===name?'level selected':'level'} key={name} onClick={()=>setLevel(name)}><span className="radio"/><span><strong>{name}</strong><small>{description}</small></span><ChevronRight size={18}/></button>)}</div><div className="assessment-note"><BookOpen size={20}/><span><strong>20 questions · about 12 minutes</strong><br/>Your results identify strengths and useful next learning steps.</span></div><div className="actions"><button className="secondary" onClick={()=>setStage(2)}><ArrowLeft size={18}/> Back</button><button className="primary" onClick={start}>Start assessment <ArrowRight size={18}/></button></div></div>}
function Assessment({questions,answers,setAnswers,submitted,setSubmitted,setStage,finish}) {const answered=Object.keys(answers).length;return <div className="panel assessment"><div className="assessment-head"><div><div className="eyebrow"><CircleHelp size={16}/> COMPETENCY CHECK</div><h1>Your personalized assessment</h1><p className="lead">Answer every question. You can review choices before submitting.</p></div><div className="counter">{answered} / {questions.length}<small>answered</small></div></div>{questions.map((q,i)=><article className="question" key={q.id}><div className="question-meta"><span>{q.category}</span><small>Question {i+1}</small></div><h3>{q.question}</h3><div className="options">{q.options.map((x,n)=><label className={answers[q.id]===n?'option chosen':'option'} key={x}><input type="radio" name={q.id} checked={answers[q.id]===n} onChange={()=>setAnswers(old=>({...old,[q.id]:n}))}/><span>{x}</span></label>)}</div></article>)}{submitted&&answered<questions.length&&<p className="error">Please answer all 20 questions before submitting.</p>}<div className="actions"><button className="secondary" onClick={()=>setStage(3)}><ArrowLeft size={18}/> Back</button><button className="primary" onClick={()=>answered===questions.length?finish():setSubmitted(true)}>See my results <Award size={18}/></button></div></div>}
function Results({account,profile,score,total,restart}) {const percent=Math.round(score/total*100), rec=profile.techSkills.includes('Python')?['Python for data analysis','Data quality and reproducible workflows',`${profile.domain} applications`]:['Data analysis fundamentals',`${profile.domain} applications`,'Data visualization for decisions'];return <main className="shell results-shell"><header><a className="brand" href="/" onClick={e=>e.preventDefault()}><span>TN</span> Tech Nova</a></header><section className="content"><div className="panel result"><div className="award"><Award size={34}/></div><div className="eyebrow">COMPETENCY PROFILE COMPLETE</div><h1>Nice work, {account.name.split(' ')[0]||'there'}.</h1><p className="lead">{percent>=75?'A strong foundation to build on.':percent>=50?'A promising foundation with clear next steps.':'A great starting point for a focused learning plan.'}</p><div className="score"><strong>{percent}%</strong><span>{score} correct out of {total}</span></div><div className="result-grid"><section><h2>Your profile</h2><p><strong>{profile.designation}</strong> · {profile.organization}</p><p>{profile.domain} · {profile.experience}</p></section><section><h2>Suggested next steps</h2>{rec.map(x=><p className="recommendation" key={x}><Check size={16}/> {x}</p>)}</section></div><div className="result-actions"><button className="secondary" onClick={restart}>Start over</button><button className="primary" onClick={()=>alert('Your learning plan would open here in the full platform.')}>View learning plan <ArrowRight size={18}/></button></div><p className="small">Frontend demonstration: data is stored only in this browser.</p></div></section></main>}
